### ISSUE TITLE
画面上に Google Map を表示したい

### ISSUE THREAD

**Issue by a-nakamura1015** [a-nakamura1015/dokoiko#1]
## 概要

- [x] WEB アプリの初期表示時に画面上に Google Map を表示する。
- [x] 位置情報をとって Google Map に現在時点を表示する。
- [x] 縮尺は道が目視確認できるレベルであればOK。
- [x] サーバーは立てずに、まずはフロントで Google Map API の動作確認をしてみる。

## 受け入れ条件

- 画面上に現在地点を Google Map にを表示できていること（縮尺は道が確認できればよい）

**Comment by y-kawase** [comment]
下記を参考に実装中
https://developers.google.com/maps/documentation/javascript/react-map?hl=ja
